### ISSUE TITLE
expose all prober functionality in python

### ISSUE THREAD

**Issue by joamatab** [SentioProberDev/SentioProberControl#3]
How could we expand all the Sentio commands into python?

Ideally we expose all the sentio software functions through the python API

this [repo](https://github.com/SentioProberDev/Examples-Python) is a good start

**Comment by beltoforion** [comment]
You can already send anyc existing remote command using the python API as shown here:

https://github.com/SentioProberDev/Examples-Python/blob/master/commands_direct_send.py

The send_cmd function will break the response apart for you and deal with extracting error, status code and message part. 

The python API is continuously expanded but not all remote commands can and will by natively supported in the python API. If you are missing support for specific commands you can either let me know here or you can talk with your MPI sales rep and let them open a ticket regarding the request.

**Comment by joamatab** [comment]
How do we find the commands available?

How can we expose them in the python driver?

**Comment by beltoforion** [comment]
I'm not sure I understand you. The "Python driver" for what? This package is the python driver for MPI SENTIO probe stations and the commands are already exposed here. It is fairly complete in terms of functionality and should already contain all functions required for normal prober operation.

The remote command specification is usually installed as a document together with a SENTIO installation. If you have access to a MPI probe station you can find it on the probe stations documentation folder. You can test it against SENTIO running in demo mode.

If you do not have a MPI probe station please ask MPI directly. To my knowledge the document in question is not publicly available but MPI may be willing to share the required information with 3rd party developers.

**Comment by beltoforion** [comment]
I have sent you an invite to a private repository where you can download the remote command specification. Please do not redistribute this document. 

I'm not sure what functionality you want to access but you will probably have to create a wafermap and a list of subsites first:

https://github.com/SentioProberDev/Examples-Python/blob/master/map_setup.py
https://github.com/SentioProberDev/Examples-Python/blob/master/map_subsite_stepping.py

We may be able to help you with specific Questions but for this we would need to understand the use case better. In order to support 3rd party development we are in principle willing make further resources available to you. (i.e. a demo version for simulating a probe station).
